/**
 * Expense Tracker API
 * REST API endpoints for Expense Tracker App
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */ /* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpEvent,
} from '@angular/common/http';
import { CustomHttpUrlEncodingCodec } from '../encoder';

import { Observable } from 'rxjs';

import { ForgotPasswordResponse } from '../model/forgotPasswordResponse';
import { SignInResponse } from '../model/signInResponse';
import { SignUp } from '../model/signUp';
import { SignUpResponse } from '../model/signUpResponse';

import { BASE_PATH, COLLECTION_FORMATS } from '../variables';
import { Configuration } from '../configuration';

@Injectable({
  providedIn: 'root',
})
export class AuthService {
  protected basePath = 'https://expense-tracker-nodejs-app.herokuapp.com';
  public defaultHeaders = new HttpHeaders();
  public configuration = new Configuration();

  constructor(
    protected httpClient: HttpClient,
    @Optional() @Inject(BASE_PATH) basePath: string,
    @Optional() configuration: Configuration
  ) {
    if (basePath) {
      this.basePath = basePath;
    }
    if (configuration) {
      this.configuration = configuration;
      this.basePath = basePath || configuration.basePath || this.basePath;
    }
  }

  /**
   * @param consumes string[] mime-types
   * @return true: consumes contains 'multipart/form-data', false: otherwise
   */
  private canConsumeForm(consumes: string[]): boolean {
    const form = 'multipart/form-data';
    for (const consume of consumes) {
      if (form === consume) {
        return true;
      }
    }
    return false;
  }

  /**
   * Send Reset Password Email.
   *
   * @param email Email ID of the user to send the reset password link.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public forgotpassword(
    email: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<ForgotPasswordResponse>;
  public forgotpassword(
    email: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<ForgotPasswordResponse>>;
  public forgotpassword(
    email: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<ForgotPasswordResponse>>;
  public forgotpassword(
    email: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (email === null || email === undefined) {
      throw new Error(
        'Required parameter email was null or undefined when calling forgotpassword.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<ForgotPasswordResponse>(
      'get',
      `${this.basePath}/forgotpassword/${encodeURIComponent(String(email))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Sign In User.
   *
   * @param creds Email ID and Password of the user.
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public signin(
    creds: any,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<SignInResponse>;
  public signin(
    creds: any,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<SignInResponse>>;
  public signin(
    creds: any,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<SignInResponse>>;
  public signin(
    creds: any,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    if (creds === null || creds === undefined) {
      throw new Error(
        'Required parameter creds was null or undefined when calling signin.'
      );
    }

    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [];

    return this.httpClient.request<SignInResponse>(
      'get',
      `${this.basePath}/users/${encodeURIComponent(String(creds))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }

  /**
   * Sign Up User.
   *
   * @param body The sign up form values
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public signup(
    body?: SignUp,
    observe?: 'body',
    reportProgress?: boolean
  ): Observable<SignUpResponse>;
  public signup(
    body?: SignUp,
    observe?: 'response',
    reportProgress?: boolean
  ): Observable<HttpResponse<SignUpResponse>>;
  public signup(
    body?: SignUp,
    observe?: 'events',
    reportProgress?: boolean
  ): Observable<HttpEvent<SignUpResponse>>;
  public signup(
    body?: SignUp,
    observe: any = 'body',
    reportProgress: boolean = false
  ): Observable<any> {
    let headers = this.defaultHeaders;

    // to determine the Accept header
    let httpHeaderAccepts: string[] = ['*/*'];
    const httpHeaderAcceptSelected: string | undefined =
      this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = ['application/json'];
    const httpContentTypeSelected: string | undefined =
      this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<SignUpResponse>(
      'post',
      `${this.basePath}/users`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress,
      }
    );
  }
}
