/**
 * Expense Tracker API
 * REST API endpoints for Expense Tracker App
 *
 * OpenAPI spec version: 0.0.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface GetExpensesData {
  response?: Array<string>;
  currentPage?: number;
  hasNextPage?: boolean;
  hasPreviousPage?: boolean;
  nextPage?: number;
  previousPage?: number;
  positive?: number;
  negative?: number;
  lastPage?: number;
  totalItems?: number;
}
